# JVM Settings for build speed
org.gradle.jvmargs=-Xmx4096m -Xms2048m -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1024m

# AndroidX configuration
android.useAndroidX=true
android.enableJetifier=false

# Enable Kotlin features
kotlin.code.style=official

# Enable KSP incremental compilation
ksp.incremental=true

android.disallowKotlinSourceSets=false

android.enableD8.desugaring=true
android.enableR8.fullMode=true
